(function(){function w(r){return function(){return this[r]}}
(function(r){function g(c,f,e){for(var b=0;b<f.length;b++)f[b]="weswit/"+f[b].replace(A,"");r("weswit/"+c,f,e)}var A=/^.\//;g("utility-toolkit",[],function(){return"1.0"});g("IllegalStateException",[],function(){function c(c){this.name="IllegalStateException";this.message=c}c.prototype={toString:function(){return["[",this.name,this.message,"]"].join("|")}};return c});g("Environment",["./IllegalStateException"],function(c){var f="undefined"!==typeof window&&navigator&&document,e="undefined"!==typeof importScripts,
b="object"==typeof process&&(/node(\.exe)?$/.test(process.execPath)||process.node&&process.v8||process.versions&&process.versions.node&&process.versions.v8);if(f&&!document.getElementById)throw new c("Not supported browser");var d={c:function(){return f},L:function(){return!b&&(f||e)},fa:function(){return!f&&b},ja:function(){return!f&&!b&&e},Aa:function(){if(!this.c())throw new c("Trying to load a browser-only module on non-browser environment");}};d.isBrowserDocument=d.c;d.isBrowser=d.L;d.isNodeJS=
d.fa;d.isWebWorker=d.ja;d.browserDocumentOrDie=d.Aa;return d});g("BrowserDetection",["./Environment"],function(c){function f(a){var b=p;return function(){null===b&&(b=-1<n.indexOf(a));return b}}function e(a){var b=p;return function(){if(null===b){b=!0;for(var d=0;d<a.length;d++)b=b&&a[d]()}return b}}function b(a,b){var d=p,c=p;return function(f,e){null===d&&(c=(d=a())?b():null);return d?f&&c?!0===e?c<=f:!1===e?c>=f:c==f:!0:!1}}function d(a){return function(){var b=a.exec(n);return b&&2<=b.length?
b[1]:null}}function a(a){return function(){return!a()}}var p=c.L()?null:!1,n=c.L()?navigator.userAgent.toLowerCase():null,k=p;c={ia:f("rekonq"),M:f("webkit"),Ya:f("playstation 3"),w:b(f("chrome/"),d(RegExp("chrome/([0-9]+)","g"))),Ta:function(){null===k&&(k=document.childNodes&&!document.all&&!navigator.kb&&!navigator.jb);return k},Wa:b(f("konqueror"),d(RegExp("konqueror/([0-9.]+)","g"))),ha:b(f("msie"),d(RegExp("msie\\s([0-9]+)[.;]","g"))),Va:b(f("firefox"),d(/firefox\/(\d+\.?\d*)/)),o:b(function(){return"undefined"!=
typeof opera},function(){if(opera.version){var a=opera.version(),a=a.replace(RegExp("[^0-9.]+","g"),"");return parseInt(a)}return 7})};c.ga=e([f("android"),c.M,a(c.w)]);c.Xa=e([c.o,f("opera mobi")]);c.Ua=b(e([f("safari"),function(a){var b=p;return function(){if(null===b){b=!1;for(var d=0;d<a.length;d++)b=b||a[d]()}return b}}([f("ipad"),f("iphone"),f("ipod"),e([a(c.ga),a(c.w),a(c.ia)])])]),d(/version\/(\d+\.?\d*)/));c.isProbablyRekonq=c.ia;c.isProbablyChrome=c.w;c.isProbablyAWebkit=c.M;c.isProbablyPlaystation=
c.Ya;c.isProbablyAndroidBrowser=c.ga;c.isProbablyOperaMobile=c.Xa;c.isProbablyApple=c.Ua;c.isProbablyAKhtml=c.Ta;c.isProbablyKonqueror=c.Wa;c.isProbablyIE=c.ha;c.isProbablyFX=c.Va;c.isProbablyOldOpera=c.o;return c});g("Helpers",["./Environment"],function(c){var f=/^\s*([\s\S]*?)\s*$/,e=/,/,b=/\./,d={J:function(){return(new Date).getTime()},na:function(a){return Math.round(Math.random()*(a||1E3))},trim:function(a){return a.replace(f,"$1")},Oa:function(a,d){if(a){if(!a.replace)return a;d?(a=a.replace(b,
""),a=a.replace(e,".")):a=a.replace(e,"");return new Number(a)}return 0},isArray:function(a){return a.join&&"function"==typeof a.join},i:function(a,b,d){if(!c.c())return!1;"undefined"!=typeof a.addEventListener?a.addEventListener(b,d,!1):"undefined"!=typeof a.attachEvent&&a.attachEvent("on"+b,d);return!0},pa:function(a,b,d){if(!c.c())return!1;"undefined"!=typeof a.removeEventListener?a.removeEventListener(b,d,!1):"undefined"!=typeof a.detachEvent&&a.detachEvent("on"+b,d);return!0}};d.getTimeStamp=
d.J;d.randomG=d.na;d.trim=d.trim;d.getNumber=d.Oa;d.isArray=d.isArray;d.addEvent=d.i;d.removeEvent=d.pa;return d});g("CookieManager",["./Helpers","./Environment"],function(c,f){var e=!1,b={l:function(){return e},$:function(){return this.l()?document.cookie.toString():null},ta:function(b,a){this.ua(b,a,"")},ua:function(b,a,c){this.l()&&(document.cookie=encodeURIComponent(b)+"\x3d"+a+"; "+c+"path\x3d/;")},Q:function(b){if(!this.l())return null;b=encodeURIComponent(b)+"\x3d";for(var a=this.$(),a=a.split(";"),
f=0;f<a.length;f++)if(a[f]=c.trim(a[f]),0==a[f].indexOf(b))return a[f].substring(b.length,a[f].length);return null},oa:function(b){if(this.l()){var a=new Date;a.setTime(a.getTime()-864E5);this.ua(b,"deleting","expires\x3d"+a.toGMTString()+"; ")}},Ba:function(){if(f.c()&&("http:"==document.location.protocol||"https:"==document.location.protocol)){e=!0;var b="LS__cookie_test"+c.na();this.ta(b,"testing");var a=this.Q(b);if("testing"==a&&(this.oa(b),a=this.Q(b),null==a))return;e=!1}}};b.Ba();b.areCookiesEnabled=
b.l;b.getAllCookiesAsSingleString=b.$;b.writeCookie=b.ta;b.removeCookie=b.oa;b.readCookie=b.Q;return b});g("List",[],function(){function c(){this.data=[]}c.prototype={add:function(c){this.data.push(c)},remove:function(c){for(var e=0;e<this.data.length;e++)if(this.data[e]==c)return this.data.splice(e,1),!0;return!1},forEach:function(c){for(var e=0;e<this.data.length;e++)c(this.data[e])},D:function(){return[].concat(this.data)},m:function(){this.data=[]}};c.prototype.add=c.prototype.add;c.prototype.remove=
c.prototype.remove;c.prototype.forEach=c.prototype.forEach;c.prototype.asArray=c.prototype.D;c.prototype.clean=c.prototype.m;return c});g("EnvironmentStatus",["./Helpers","./BrowserDetection","./Environment","./List"],function(c,f,e,b){function d(a,b,c,d,f){return function(){a[b]||(a[c]=!0,d.forEach(function(a){try{if(a[f])a[f]();else a()}catch(b){}}),"preunloading"!=b&&d.m(),a[b]=!0,a[c]=!1)}}function a(a,b){setTimeout(function(){if(a[b])a[b]();else a()},0)}function p(a,b,c,d){setTimeout(function(){c?
d?a.apply(c,d):a.apply(c):d?a.apply(null,d):a()},b)}function n(){g=!0}var k=new b,m=new b,q=new b,g=!1,u={p:"onloadDone",la:"onloadInprogress",t:"unloaded",T:"unloading",ma:"preunloading"};b={};for(var h in u)b[u[h]]=h;h={p:!1,la:!1,t:!1,T:!1,ma:!1,Qa:w("p"),Za:w("t"),$a:w("T"),xa:function(b){this.Ra()?m.add(b):a(b,"onloadEvent")},U:function(b){this.Sa()?k.add(b):a(b,"unloadEvent")},wa:function(b){q.add(b);this.ma&&a(b,"preUnloadEvent")},cb:function(a){m.remove(a)},fb:function(a){k.remove(a)},bb:function(a){q.remove(a)},
Ra:function(){return!(this.p||this.la)},Sa:function(){return!(this.t||this.T)},ya:function(){c.i(window,"unload",this.Ca);c.i(window,"beforeunload",this.za);if(document&&"undefined"!=typeof document.readyState){if("COMPLETE"==document.readyState.toUpperCase()){this.u();return}p(this.W,1E3,this)}else if(this.ea()){this.u();return}if(!c.i(window,"load",this.A))this.u();else if(f.o()){var a=!1;f.o(9,!1)&&(a=!0,c.i(document,"DOMContentLoaded",n));p(this.V,1E3,this,[a])}},u:function(){p(this.A,0)},W:function(){this.p||
("COMPLETE"==document.readyState.toUpperCase()?this.A():p(this.W,1E3,this))},V:function(a){this.p||(g||!a&&this.ea()?this.A():p(this.V,1E3,this,[a]))},ea:function(){return"undefined"!=typeof document.getElementsByTagName&&"undefined"!=typeof document.getElementById&&(null!=document.getElementsByTagName("body")[0]||null!=document.body)}};h.A=d(h,b.onloadDone,b.onloadInprogress,m,"onloadEvent");h.Ca=d(h,b.unloaded,b.unloading,k,"unloadEvent");h.za=d(h,b.preunloading,b.preunloading,q,"preUnloadEvent");
e.c()?h.ya():h.u();h.addOnloadHandler=h.xa;h.addUnloadHandler=h.U;h.addBeforeUnloadHandler=h.wa;h.removeOnloadHandler=h.cb;h.removeUnloadHandler=h.fb;h.removeBeforeUnloadHandler=h.bb;h.isLoaded=h.Qa;h.isUnloaded=h.Za;h.isUnloading=h.$a;return h});g("Executor",["./Helpers","./EnvironmentStatus","./Environment"],function(c,f,e){function b(){}function d(a,b){return a.time===b.time?a.P-b.P:a.time-b.time}function a(){t=!1;n()}function p(){if(x)clearInterval(x);else if(e.c()&&"undefined"!=typeof postMessage){v=
function(){window.postMessage("Lightstreamer.run",z)};var d=function(b){("Lightstreamer.run"==b.data&&"*"==z||b.origin==z)&&a()};c.i(window,"message",d);t||(t=!0,v());!1==t&&(c.pa(window,"message",d),v=b)}else e.fa()&&("undefined"!=typeof process&&process.nextTick)&&(v=function(){process.nextTick(a)});x=setInterval(n,k)}function n(){if(f.t)clearInterval(x);else{s=c.J();if(0<g.length){m&&(g.sort(d),m=!1);for(var a;0<g.length&&g[0].time<=s&&!f.t;)a=g.shift(),a.b&&(l.n(a),a.step&&r.push(a))}for(0>=g.length&&
(y=0);0<r.length;)a=r.shift(),a.P=y++,l.d(a,a.step,!0);s>=h&&(h=s+u,g=[].concat(g))}}var k=50,m=!1,g=[],s=c.J(),u=108E5,h=s+u,r=[],x=null,y=0,z=!e.c()||"http:"!=document.location.protocol&&"https:"!=document.location.protocol?"*":document.location.protocol+"//"+document.location.hostname+(document.location.port?":"+document.location.port:""),v=b,t=!1,l={toString:function(){return["[|Executor",k,g.length,"]"].join("|")},I:function(){return g.length},q:function(a,b,c){return{b:a,f:b||null,h:c||null,
P:y++}},d:function(a,b,c){a.step=c?b:null;a.time=s+parseInt(b);if(isNaN(a.time))throw"Executor error time: "+a.time;g.push(a);m=!0},C:function(a,b,c,d){return this.e(a,b,c,d,!0)},R:function(a){a&&(a.b=null,a.step=null)},e:function(a,b,c,d,f){a=this.q(a,c,d);this.d(a,b,f);0!=b||t||(t=!0,v());return a},O:function(a,b,c){a.h[b]=c},N:function(a,b){a.h=b},G:function(a,b){a.time+=b;m=!0},n:function(a,b){try{var c=b||a.h;a.f?c?a.b.apply(a.f,c):a.b.apply(a.f):c?a.b.apply(null,c):a.b()}catch(d){}}};e.ja()?
setTimeout(p,1):p();l.getQueueLength=l.I;l.packTask=l.q;l.addPackedTimedTask=l.d;l.addRepetitiveTask=l.C;l.stopRepetitiveTask=l.R;l.addTimedTask=l.e;l.modifyTaskParam=l.O;l.modifyAllTaskParams=l.N;l.delayTask=l.G;l.executeTask=l.n;return l});g("Dismissable",["./Executor"],function(c){function f(){this.da()}f.prototype={m:function(){},da:function(c){this.S=this.k=0;this.timeout=c||5E3},ib:function(c){c==this.S&&0>=this.k&&this.m()},Ea:function(){this.k--;0>=this.k&&c.e(this.ib,this.timeout,this,[this.S])},
gb:function(){this.S++;0>this.k&&(this.k=0);this.k++}};f.prototype.touch=f.prototype.gb;f.prototype.dismiss=f.prototype.Ea;f.prototype.clean=f.prototype.m;f.prototype.initTouches=f.prototype.da;return f});g("Inheritance",["./IllegalStateException"],function(c){function f(b,c,a){if(c)return a?c.apply(b,a):c.apply(b)}var e={va:function(b,d,a,f){for(var n in d.prototype)if(!b.prototype[n])b.prototype[n]=d.prototype[n];else if(f){var k;a:{k=d.prototype;var g=void 0;for(g in k)if(k[n]==k[g]&&n!=g){k=g;
break a}k=null}if(k){if(b.prototype[k]&&b.prototype[k]!==b.prototype[n]&&d.prototype[k]!==d.prototype[k])throw new c("Can't solve alias collision, try to minify the classes again ("+k+", "+n+")");b.prototype[k]=b.prototype[n]}}a||(b.prototype._super_=d,b.prototype._callSuperConstructor=e._callSuperConstructor,b.prototype._callSuperMethod=e._callSuperMethod)},_callSuperMethod:function(b,c,a){return f(this,b.prototype._super_.prototype[c],a)},_callSuperConstructor:function(b,c){f(this,b.prototype._super_,
c)}};return e.va});g("Matrix",[],function(){function c(c){this.a=c||{}}c.prototype={K:function(c,e,b){e in this.a||(this.a[e]={});this.a[e][b]=c},get:function(c,e){return c in this.a&&e in this.a[c]?this.a[c][e]:null},v:function(c,e){if(!(!c in this.a)){e in this.a[c]&&delete this.a[c][e];for(var b in this.a[c])return;delete this.a[c]}},insertRow:function(c,e){this.a[e]=c},ba:function(c){return c in this.a?this.a[c]:null},F:function(c){c in this.a&&delete this.a[c]},La:w("a"),Pa:function(){for(var c in this.a)return!1;
return!0},Ia:function(c){for(var e in this.a)this.Z(e,c)},Ka:function(c){for(var e in this.a)c(e)},Z:function(c,e){var b=this.a[c],d;for(d in b)e(b[d],c,d)}};c.prototype.insert=c.prototype.K;c.prototype.get=c.prototype.get;c.prototype.del=c.prototype.v;c.prototype.insertRow=c.prototype.insertRow;c.prototype.getRow=c.prototype.ba;c.prototype.delRow=c.prototype.F;c.prototype.getEntireMatrix=c.prototype.La;c.prototype.forEachElement=c.prototype.Ia;c.prototype.forEachElementInRow=c.prototype.Z;c.prototype.forEachRow=
c.prototype.Ka;c.prototype.isEmpty=c.prototype.Pa;return c});g("DoubleKeyMatrix",["./Inheritance","./Matrix"],function(c,f){function e(){this._callSuperConstructor(e);this.r={}}e.prototype={K:function(b,c,a){"undefined"==typeof this.r[a]&&(this.r[a]=c,this._callSuperMethod(e,"insert",[b,c,a]))},v:function(b,c){this._callSuperMethod(e,"del",[b,c]);delete this.r[c]},Da:function(b){var c=this.r[b];"undefined"!=typeof c&&this.v(c,b)},F:function(b){var c=this.ba(b),a;for(a in c)delete this.r[a];this._callSuperMethod(e,
"delRow",[b])}};e.prototype.insert=e.prototype.K;e.prototype.del=e.prototype.v;e.prototype.delReverse=e.prototype.Da;e.prototype.delRow=e.prototype.F;c(e,f);return e});g("IllegalArgumentException",[],function(){function c(c){this.name="IllegalArgumentException";this.message=c}c.prototype={toString:function(){return["[",this.name,this.message,"]"].join("|")}};return c});g("DoubleKeyMap",["./IllegalArgumentException"],function(c){function f(){this.map={};this.s={}}function e(a){return null!==a&&"undefined"!=
typeof a}function b(a,b,c){var d=a[c];e(d)&&(delete a[c],delete b[d])}function d(a,b){for(var c in a)b(c,a[c])}f.prototype={set:function(a,b){var d=this.map,f=this.s;if(!e(a)||!e(b))throw new c("values can't be null nor missing");var g=d[a],q=f[b];e(g)?g!==b&&(e(q)?(d[q]=g,d[a]=b,f[b]=a,f[g]=q):(delete f[d[a]],d[a]=b,f[b]=a)):e(q)?(delete d[f[b]],f[b]=a,d[a]=b):(d[a]=b,f[b]=a)},remove:function(a){b(this.map,this.s,a)},eb:function(a){b(this.s,this.map,a)},get:function(a){return this.map[a]},aa:function(a){return this.s[a]},
Ga:function(a){return"undefined"!=typeof this.get(a)},Ha:function(a){return"undefined"!=typeof this.aa(a)},forEach:function(a){d(this.map,a)},Ja:function(a){d(this.s,a)}};f.prototype.set=f.prototype.set;f.prototype.remove=f.prototype.remove;f.prototype.removeReverse=f.prototype.eb;f.prototype.get=f.prototype.get;f.prototype.getReverse=f.prototype.aa;f.prototype.exist=f.prototype.Ga;f.prototype.existReverse=f.prototype.Ha;f.prototype.forEach=f.prototype.forEach;f.prototype.forEachReverse=f.prototype.Ja;
return f});g("EventDispatcher",["./Executor","./List","./Inheritance"],function(c,f,e){function b(){this._callSuperConstructor(b)}function d(){this.ca()}d.prototype={ca:function(){this.B=new b;this.sa=!1},addListener:function(a){a&&(a={g:a,ka:!0},this.B.add(a),this.H("onListenStart",[this],a,!0))},removeListener:function(a){a&&(a=this.B.remove(a))&&this.H("onListenEnd",[this],a,!0)},Na:function(){return this.B.D()},hb:function(a){this.sa=!0===a},H:function(a,b,d,e){this.sa?this.Y(a,b,d,!0):c.e(this.Y,
0,this,[a,b,d,e])},Y:function(a,b,c,d){if(c&&c.g[a]&&(d||c.ka))try{b?c.g[a].apply(c.g,b):c.g[a].apply(c.g)}catch(e){}},dispatchEvent:function(a,b){var c=this;this.B.forEach(function(d){c.H(a,b,d,!1)})}};d.prototype.initDispatcher=d.prototype.ca;d.prototype.addListener=d.prototype.addListener;d.prototype.removeListener=d.prototype.removeListener;d.prototype.getListeners=d.prototype.Na;d.prototype.useSynchEvents=d.prototype.hb;d.prototype.dispatchEvent=d.prototype.dispatchEvent;b.prototype={remove:function(a){for(var b=
0;b<this.data.length;b++)if(this.data[b].g==a)return a=this.data[b],a.ka=!1,this.data.splice(b,1),a;return!1},D:function(){var a=[];this.forEach(function(b){a.push(b.g)});return a}};e(b,f);return d});g("ExecutorSimple",[],function(){function c(b){return function(){b.j?(b.time=b.j,b.j=0,e.d(b,b.time,!1)):(e.n(b),b.ra||f--)}}var f=0,e={toString:function(){return"[|ExecutorSimple|]"},I:function(){return f},q:function(b,c,a){return{b:b,f:c||null,h:a||null}},d:function(b,d,a){b.time=d;if(isNaN(b.time))throw"ExecutorSimple error time: "+
b.time;b.ra=a;f++;b.ab=a?setInterval(c(b),b.time):setTimeout(c(b),b.time)},C:function(b,c,a,e){return this.e(b,c,a,e,!0)},R:function(b){b&&(clearInterval(b.ab),f--)},e:function(b,c,a,e,f){b=this.q(b,a,e);this.d(b,c,f);return b},O:function(b,c,a){b.h[c]=a},N:function(b,c){b.h=c},G:function(b,c){if(b.ra)throw"Can't delay repetitive tasks";b.j||(b.j=0);b.j+=c},n:function(b,c){try{var a=c||b.h;b.f?a?b.b.apply(b.f,a):b.b.apply(b.f):a?b.b.apply(null,a):b.b()}catch(e){}}};e.getQueueLength=e.I;e.packTask=
e.q;e.addPackedTimedTask=e.d;e.addRepetitiveTask=e.C;e.stopRepetitiveTask=e.R;e.addTimedTask=e.e;e.modifyTaskParam=e.O;e.modifyAllTaskParams=e.N;e.delayTask=e.G;e.executeTask=e.n;return e});g("IFrameHandler",["./BrowserDetection","./EnvironmentStatus","./Environment"],function(c,f,e){var b=c.M()&&c.w(32,!0)?null:"about:blank",d={},a={X:function(a,f){if(!e.c())return null;var g=document.getElementsByTagName("BODY")[0];if(!g)return null;f=f||b;var m=document.createElement("iframe");m.style.visibility=
"hidden";m.style.height="0px";m.style.width="0px";m.style.display="none";m.name=a;m.id=a;c.ha()||c.o()?(m.src=f,g.appendChild(m)):(g.appendChild(m),m.src=f);try{if(m.contentWindow){try{m.contentWindow.name=a}catch(q){}d[a]=m.contentWindow;return d[a]}return document.frames&&document.frames[a]?(d[a]=document.frames[a],d[a]):null}catch(r){return null}},Ma:function(a,b,c){b&&!d[a]&&this.X(a,c);return d[a]||null},Fa:function(a){if(d[a]){try{document.getElementsByTagName("BODY")[0].removeChild(document.getElementById(a))}catch(b){}delete d[a]}},
qa:function(){for(var a in d)try{document.getElementsByTagName("BODY")[0].removeChild(document.getElementById(a))}catch(b){}d={}}};a.createFrame=a.X;a.getFrameWindow=a.Ma;a.disposeFrame=a.Fa;a.removeFrames=a.qa;f.U(a.qa);return a});g("Setter",["./IllegalArgumentException"],function(c){function f(){}f.prototype.checkPositiveNumber=function(e,b,d){var a=new Number(e);if(isNaN(a))throw new c("The given value is not valid. Use a number");if(!d&&a!=Math.round(a))throw new c("The given value is not valid. Use an integer");
if(b){if(0>e)throw new c("The given value is not valid. Use a positive number or 0");}else if(0>=e)throw new c("The given value is not valid. Use a positive number");return a};f.prototype.checkBool=function(e,b){if(!0===e||!1===e||b&&!e)return!0===e;throw new c("The given value is not valid. Use true or false");};return f})})(define);}());
//# sourceMappingURL=utility-toolkit.js.map